- api/src/main/resources/messages.properties
- omod/src/main/webapp/mapPatientIdentifierForm.jsp
- omod/src/main/webapp/resources/css/disa.css
- omod/src/main/webapp/viralLoadResultsList.jsp
> DOI-30: Add pagination on DISA to OpenMRS NID mapping tables

- omod/src/main/java/org/openmrs/module/disa/extension/util/Constants.java
- omod/src/main/java/org/openmrs/module/disa/scheduler/ViralLoadFormSchedulerTask.java
- omod/src/test/java/org/openmrs/module/disa/scheduler/ViralLoadFormSchedulerTaskTest.java
Mudou-se os `System.out.println()` para `log.info()`, mas para as mensagens aparecerem no log é preciso alterar a `global_property` `log.level` e adicionar `,org.openmrs.module.disa:info`.
> DOI-82 Handle >10 000 000 on VL sync algorithm

- api/.classpath
- api/src/main/resources/liquibase.xml
- omod/src/main/java/org/openmrs/module/disa/web/delegate/ManageVLResultsDelegate.java
- omod/src/main/webapp/managelabresults/index.jsp
- omod/src/main/webapp/managelabresults/reallocate.jsp
- omod/src/main/webapp/mapunprocessed/viralLoadStatusList.jsp
- omod/src/main/webapp/searchlabresults/viralLoadStagingServer.jsp
Create specific role for Disa Interoperability managers
> DOI-71 Create and enforce manage VL Results privilege

- omod/src/main/java/org/openmrs/module/disa/extension/util/DateUtil.java
- omod/src/main/java/org/openmrs/module/disa/scheduler/ViralLoadFormSchedulerTask.java
Set obs datetime and value datetime to midnight
> DOI-89 Set FSR encounter date time to start of day

- omod/src/main/webapp/managelabresults/index.jsp
Correct available manage options per result status
> DOI-72 Reschedule VL Result

- api/src/main/resources/liquibase.xml
> DOI-70 Manage VL results on integration server

- omod/src/main/java/org/openmrs/module/disa/web/config/DisaWebConfig.java
Disable favoring of path extensions
> Fix visits tab

- api/src/main/java/org/openmrs/module/disa/CD4LabResult.java
- api/src/main/java/org/openmrs/module/disa/HIVVLLabResult.java
- api/src/main/java/org/openmrs/module/disa/LabResult.java
- api/src/main/java/org/openmrs/module/disa/TypeOfResult.java
- api/src/main/java/org/openmrs/module/disa/api/DisaService.java
- api/src/main/java/org/openmrs/module/disa/api/LabResultService.java
- api/src/main/java/org/openmrs/module/disa/api/client/DisaAPIHttpClient.java
- api/src/main/java/org/openmrs/module/disa/api/config/DisaModuleAPIConfig.java
- api/src/main/java/org/openmrs/module/disa/api/impl/DisaServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/impl/LabResultServiceImpl.java
- api/src/main/resources/messages.properties
- api/src/main/resources/messages_pt.properties
- api/src/test/java/org/openmrs/module/disa/api/DisaServiceImplTest.java
- api/src/test/java/org/openmrs/module/disa/api/LabResultServiceImplTest.java
- omod/src/main/java/cl/ciochile/victoraravena/ApiAuthRest.java
- omod/src/main/java/org/openmrs/module/disa/extension/util/RestUtil.java
- omod/src/main/java/org/openmrs/module/disa/scheduler/ViralLoadFormSchedulerTask.java
- omod/src/main/java/org/openmrs/module/disa/web/controller/DisaModuleControllerAdvice.java
- omod/src/main/java/org/openmrs/module/disa/web/controller/ManageLabResultsController.java
- omod/src/main/java/org/openmrs/module/disa/web/controller/MapUnprocessedLabResultsController.java
- omod/src/main/java/org/openmrs/module/disa/web/controller/ReallocateLabResultsController.java
- omod/src/main/java/org/openmrs/module/disa/web/delegate/ViralLoadResultsDelegate.java
- omod/src/main/webapp/managelabresults/index.jsp
- omod/src/main/webapp/managelabresults/map.jsp
- omod/src/test/java/org/openmrs/module/disa/scheduler/ViralLoadFormSchedulerTaskTest.java
* Rename Disa to LabResult, rename generic lab result properties
* Add summary at end of sync
* Add subclasses for CD4 and HIV Viral Load lab results
* Remove unused excel report
* Refactor map, re-schedule and reallocate
> DOI-153 Adapt current VL Data structure to receive also CD4 results

- api/src/main/java/org/openmrs/module/disa/api/impl/DisaServiceImpl.java
* Fetch patients with active identifiers
> DOI-121 Handle patients without identifiers when mapping NIDs

- api/src/main/java/org/openmrs/module/disa/api/DisaService.java
- api/src/main/java/org/openmrs/module/disa/api/impl/DisaServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/sync/FinalLabResultHandler.java
- api/src/test/java/org/openmrs/module/disa/api/sync/DisaServiceUnitTest.java
- api/src/test/java/org/openmrs/module/disa/api/sync/FinalLabResultHandlerTest.java
- omod/src/main/java/org/openmrs/module/disa/scheduler/ViralLoadFormSchedulerTask.java
* Move processed result algorithm to DisaService
> DOI-156 Successfully processed results that are currently in a pending state

- api/src/main/java/org/openmrs/module/disa/SyncLog.java
- api/src/main/java/org/openmrs/module/disa/api/DisaService.java
- api/src/main/java/org/openmrs/module/disa/api/db/DisaDAO.java
- api/src/main/java/org/openmrs/module/disa/api/db/hibernate/HibernateDisaDAO.java
- api/src/main/java/org/openmrs/module/disa/api/impl/DisaServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/sync/CD4LabResultHandler.java
- api/src/main/java/org/openmrs/module/disa/api/sync/HIVVLLabResultHandler.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/disa/api/sync/DisaServiceUnitTest.java
- api/src/test/java/org/openmrs/module/disa/api/sync/HIVVLLabResultHandlerTest.java
* Handle different spellings of copies/ml
* Not saving fields removed from e-lab form
* Rename fsr_log to disa_sync_log
> DOI-184 Adapt HIV VL results sync to eLab form

- omod/src/main/webapp/managelabresults/reallocate.jsp
> DOI-168 Investigate solution for managing OrgUnits table

- api/src/main/java/org/openmrs/module/disa/HIVVLLabResult.java
- api/src/main/java/org/openmrs/module/disa/LabResult.java
- api/src/main/java/org/openmrs/module/disa/api/LabResultService.java
- api/src/main/java/org/openmrs/module/disa/api/client/DisaAPIHttpClient.java
- api/src/main/java/org/openmrs/module/disa/api/impl/DisaServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/impl/LabResultServiceImpl.java
- api/src/test/java/org/openmrs/module/disa/api/DisaServiceImplTest.java
- api/src/test/java/org/openmrs/module/disa/api/LabResultServiceImplTest.java
- omod/src/main/java/org/openmrs/module/disa/web/controller/ManageLabResultsController.java
- omod/src/main/java/org/openmrs/module/disa/web/controller/MapUnprocessedLabResultsController.java
- omod/src/main/java/org/openmrs/module/disa/web/controller/ReallocateLabResultsController.java
- omod/src/main/webapp/managelabresults/index.jsp
- omod/src/main/webapp/managelabresults/map.jsp
- omod/src/main/webapp/resources/css/disa.css
* Use id to perform reschedule, reallocate and remove
> DOI-185 Add unique constraint (RequestId, TypeOfResult)

- api/src/main/java/org/openmrs/module/disa/DisaModuleActivator.java
- api/src/main/java/org/openmrs/module/disa/api/client/ApiPasswordGPListener.java
- api/src/main/java/org/openmrs/module/disa/api/client/ApiUrlGPListener.java
- api/src/main/java/org/openmrs/module/disa/api/client/ApiUsernameGPListener.java
- api/src/main/java/org/openmrs/module/disa/api/client/DisaAPIHttpClient.java
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/webapp/managelabresults/index.jsp
* Correctly inform of unauthorized HF
* Configure API client at module startup
* Listen to url, username and password global property changes
> DOI-186 Prepare credentials for implementing partners

- api/src/main/java/org/openmrs/module/disa/api/report/StagingServerReport.java
- api/src/main/resources/messages.properties
- api/src/main/resources/messages_pt.properties
- omod/src/main/webapp/managelabresults/index.jsp
* Add harvest date to search interface and export
> DOI-193 Show Data da Colheita on manage results

- api/src/main/java/org/openmrs/module/disa/api/config/DisaModuleAPIConfig.java
* Serialize only non-null properties by default
> DOI-216 Migrate HTTP client to rest template

- api/src/main/java/org/openmrs/module/disa/api/DisaService.java
- api/src/main/java/org/openmrs/module/disa/api/LabResult.java
- api/src/main/java/org/openmrs/module/disa/api/SyncLog.java
- api/src/main/java/org/openmrs/module/disa/api/db/DisaDAO.java
- api/src/main/java/org/openmrs/module/disa/api/db/hibernate/HibernateDisaDAO.java
- api/src/main/java/org/openmrs/module/disa/api/impl/DisaServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/impl/LabResultServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/sync/DuplicateRequestIdLookup.java
- api/src/test/java/org/openmrs/module/disa/api/SyncLogTest.java
- api/src/test/java/org/openmrs/module/disa/api/sync/DisaServiceUnitTest.java
- api/src/test/java/org/openmrs/module/disa/api/sync/DuplicateRequestIdLookupTest.java
- omod/pom.xml
- omod/src/main/java/org/openmrs/module/disa/web/controller/ManageLabResultsController.java
- omod/src/main/webapp/managelabresults/index.jsp
- omod/src/main/webapp/managelabresults/map.jsp
- omod/src/test/java/org/openmrs/module/disa/web/controller/ManageLabResultsControllerTest.java
- pom.xml
* Rename old FSR log methods
* Load encounters from lab results
* Unit test ManageLabResultsController
> DOI-220 Add link to eLab in search and link to patient in mapping interface

- omod/src/main/java/org/openmrs/module/disa/web/controller/ReallocateLabResultsController.java
* Manually validade ReallocateForm
> DOI-224 Reallocation: Treat input of special characters in HF field

- api/src/main/java/org/openmrs/module/disa/api/impl/OrgUnitServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/report/StagingServerReport.java
- api/src/main/resources/liquibase.xml
- omod/src/main/java/org/openmrs/module/disa/web/controller/ManageLabResultsController.java
* Fix disa sync log
* Handle client errors on OrgUnit endpoint
* Change sheet name on staging server report
> DOI-226 Regression testing fixes

- api/src/main/java/org/openmrs/module/disa/api/util/NotificationUtil.java
- api/src/main/java/org/openmrs/module/disa/api/util/Notifier.java
- api/src/test/java/org/openmrs/module/disa/api/util/NotifierTest.java
* Check if recipients empty
* Refactor and test NotificationUtil
> DOI-238 Do not send emails when recipients empty

- api/src/main/java/org/openmrs/module/disa/api/DisaService.java
- api/src/main/java/org/openmrs/module/disa/api/db/DisaDAO.java
- api/src/main/java/org/openmrs/module/disa/api/db/hibernate/HibernateDisaDAO.java
- api/src/main/java/org/openmrs/module/disa/api/impl/DisaServiceImpl.java
- api/src/main/java/org/openmrs/module/disa/api/sync/SyncStatus.java
- api/src/main/java/org/openmrs/module/disa/api/sync/SyncStatusService.java
- api/src/main/java/org/openmrs/module/disa/api/sync/scheduler/ViralLoadFormSchedulerTask.java
- api/src/main/resources/messages.properties
- api/src/main/resources/messages_pt.properties
- api/src/test/java/org/openmrs/module/disa/api/LabResultServiceImplTest.java
- api/src/test/java/org/openmrs/module/disa/api/sync/SyncStatusServiceTest.java
* Fetch repeat interval from the database
> DOI-233 Sync process informative messages

- omod/src/main/webapp/managelabresults/map.jsp
- omod/src/main/webapp/resources/js/mapIdentifiers.js
* Move mapping js code to own file
* Remove default ordering
> DOI-237 Mapeamento de NID: Interface enhancement

- api/src/main/java/org/openmrs/module/disa/DisaModuleActivator.java
- api/src/main/java/org/openmrs/module/disa/api/client/DisaAPIHttpClientConfigurer.java
- api/src/main/java/org/openmrs/module/disa/api/sync/scheduler/ViralLoadFormSchedulerTask.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/disa/api/sync/scheduler/ViralLoadFormSchedulerTaskTest.java
* Load environment variables on module startup
* Remove username and password from global_properties
> DOI-231 Use environment variables instead of global properties

- api/src/main/java/org/openmrs/module/disa/api/config/DisaModuleAPIConfig.java
- api/src/main/java/org/openmrs/module/disa/api/config/DisaUserAgentInterceptor.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/disa/config/DisaUserAgentInterceptorTest.java
* Implement ClientHttpRequestInterceptor to set user agent for all requests
* Configure interceptor to use artifactId/version as the user agent value
> DOI-241 Add module version to user agent

- omod/src/main/webapp/resources/js/mapIdentifiers.js
> DOI-237 Mapeamento de NID Interface enhancement

- api/src/main/java/org/openmrs/module/disa/api/sync/PatientNidLookup.java
- api/src/main/java/org/openmrs/module/disa/api/sync/scheduler/ViralLoadFormSchedulerTask.java
- api/src/main/java/org/openmrs/module/disa/api/util/NotificationUtil.java
- api/src/main/java/org/openmrs/module/disa/api/util/Notifier.java
- api/src/test/java/org/openmrs/module/disa/api/sync/PatientNidLookupTest.java
- api/src/test/java/org/openmrs/module/disa/api/util/NotifierTest.java
Ensure notifications are working on disa-module and disa-notofication
> DOI-300 Ensure notifications are working on disa-module and disa-notofication

- omod/src/main/resources/elab.htmlform
* Harmonize with Laboratório geral form
> DOI-308 Add CD4 semi-quantitative to eLab htmlform

- api/pom.xml
- omod/pom.xml
- pom.xml
> Prepare for version 2.7.0

- omod/src/main/resources/elab.htmlform
* Group TBLAM result with positivity level
> DOI-315 Use ConvSets for TBLAM results
